move it ! :)
juliushaertl/direct_menu pull request #55
Opened 2017-02-21 17:31 UTC by blackcrack

Hi,

i have move the menu more in right direction
and have remove the space between the front
to be better skinable and to be not over the title of the heading :)
now fit's also for skinning :)
best regards
Blacky

2017-02-21 18:23 UTC, blackcrack commented
and have update the commit again, because,
to be more fail free ;)

best regards
Blacky

2017-02-22 09:19 UTC, juliushaertl commented
@blackcrack Thanks for the contribution, although i don't get the original problem with the direct_menu app, moving the margin to the #navigation element seems fine to me. Can you comment on why the  padding-right is required?

2017-02-22 09:19 UTC, juliusknorr requested changes

2017-02-22 09:19 UTC, juliushaertl commented on templates/direct_menu.php
> +		padding-right:10px;
What is the reason for the right padding? Should work fine without. :wink:

2017-02-22 09:19 UTC, juliushaertl commented on templates/direct_menu.php
> +                margin-left: 170px;
:+1: Makes sense to have the margin with the #navigation element

2017-02-22 17:22 UTC, blackcrack commented on templates/direct_menu.php
> +		padding-right:10px;
what, was an less space between the icons and have not look very nice, so with 10 px by side, look's better, uniform and smooth.. try it out, be just 10 px, but this maks's it.. :)

best regards
blacky

2017-02-22 17:22 UTC, blackcrack commented on templates/direct_menu.php
> +                margin-left: 170px;
thy :)

2017-03-16 10:44 UTC, juliushaertl commented on templates/direct_menu.php
> +		padding-right:10px;
the padding right on the <ul> element is not affecting the space between the icons, it is just the space after the last icon, which has no influence on the vanilla nextcloud theme. :wink: See comments on #54 on how you can integrate this withing your theme.

2017-07-06 10:54 UTC, juliushaertl commented
Closing since direct_menu will not be developed further.

2017-07-06 10:54 UTC, closed without merging